### ISSUE TITLE
Access masscan through API from Rust or C

### ISSUE THREAD

**Issue by adrianbrink** [robertdavidgraham/masscan#236]
Hi,

I am trying to write a small utility that accepts a list of ports and then scans the specified IP address ranges for it. When it gets a response it should try and connect according to some strategy (just open access; default access) and then take a screen shot.

> For example: You would specify port 5900, look for all VNC clients on the network. Once you find one, you try and connect and on successful connection take a screenshot and then save the time, ip address, port number and screen shot.

My question/request/info-needed is how I would accomplish that with masscan. Is there an undocumented API or some branch that opens an API?

Any pointers to similar projects, feedback or general tips would be appeciated.

Kind Regards,
Adrian

**Comment by agreene5** [comment]
The way I do this is by writing a wrapper around masscan. I abstract most of it via my own API which is a glorified Popen wrapper written as a generator in Python and ultimate ingest the results from JSON. I then have a bunch of post-processing scripts that do what you describe- perform additional layer 7 checks on the services, or enrich the layer 7 information masscan already provides (i.e. translate a cipher number to an actual cipher-suite string likes TLS_RSA_WITH_CAMELLIA_128_CBC_SHA, do some sanitization of 'binary' banners that were grabbed such as telnet) 

Some of the 'active' things you can do postprocessing are as you describe- for example, it's quick easy to grab headers and HTML content from HTTPS endpoints, check VNC for advertised authentication methods, etc. from other tools once you have the port information.

I think trying to hook into masscan is not what you want to do here... just let masscan run and then postprocess the results.

I've found https://github.com/zmap/zgrab to be useful for some of this. Occasionally nmap is helpful, though I try to avoid it as much as possible because it is slow and the output formats are generally terrible to parse for layer 7 type information. For example, their XML format is awful..

Hope this is helpful..

**Comment by agreene5** [comment]
You also have the option of adding the functionality you need to masscan- see their layer-7 stuff, and their "--script" stuff, such as script-ntp-monlist.c

But again, I don't think this is the road you want to go down..
