### ISSUE TITLE
Segmentation fault on Debian 8 when using pfring

### ISSUE THREAD

**Issue by megapro17** [robertdavidgraham/masscan#279]
```
root# masscan -iL Input.txt --open --rate 100000000 -p8000 --pfring
======================================================================
 Segmentation fault: please post this backtrace to:
 https://github.com/robertdavidgraham/masscan/issues
======================================================================
7: [masscan() [0x403617]]
?? ??:0
6: [/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf5) [0x7fd3504d9b45]]
?? ??:0
5: [masscan() [0x402e98]]
?? ??:0
4: [masscan() [0x41c62a]]
?? ??:0
3: [masscan() [0x417cff]]
?? ??:0
2: [/lib/x86_64-linux-gnu/libc.so.6(+0x350e0) [0x7fd3504ed0e0]]
?? ??:0
1: [masscan() [0x40e5b3]]
?? ??:0
```

Without --pfring works normal. Pfring version: pfring-dkms_6.7.0_all.deb and pfring_6.7.0-1251_amd64.deb.

ii  pfring                                6.7.0-1251                           amd64        PF_RING (http://www.ntop.org/pf_ring/) [dev:3e347761f9d11c743f0f90bbd08beb562150b023 (Sat Jun 3 18:16:02 2017 +0200)]
ii  pfring-dkms                           6.7.0                                all          PF_RING driver in DKMS format. GIT info: dev:3e347761f9d11c743f0f90bbd08beb562150b023 (Sat Jun 3 18:16:02 2017 +0200)

**Comment by mzpqnxow** [comment]
I recommend building pfring from source and not using the pre-built package. I don't use packaged pfring anymore for this reason. I didn't bother to get to the root cause, sorry. I just noticed that in my case, an `ioctl()` was failing shortly before the crash. The ioctl() appeared to be coming from the pfring libraries, not masscan code
