### ISSUE TITLE
Option to split the output file progressively during scan ?

### ISSUE THREAD

**Issue by adrianTNT** [robertdavidgraham/masscan#363]
When you run a large search it doesn't work right to try to fetch unfinished progress because it's hard to tell what data was already processed, etc. 

Is there an option (or can an option be added ?) so that when you specify the output file you also get the option to split the file every x lines ?

e.g ```-oG result.txt --output-lines 1000```

```
result.txt
result.txt.1
resutl.txt.2
result.txt.3
```
And in a way so that you can easy take/move/delete the result.txt or result.txt.1 from there without breaking the scan in progress.

**Comment by mzpqnxow** [comment]
Use GNU split and cat to rejoin

**Comment by adrianTNT** [comment]
You mean the result and not during scan in progress, right ?

**Comment by mzpqnxow** [comment]
Yes

**Comment by robertdavidgraham** [comment]
You can use the "rotate" feature.  This cleanly closes the current file, renames it, then opens a new output file.  For example:

masscan 23.23.23.0/24 -p80 -oX foo.xml --rotate 1

This produced the following files:
180723-164910-foo.xml		
180723-164911-foo.xml	
180723-164912-foo.xml
180723-164913-foo.xml
180723-164924-foo.xml

The rotated filename is <year><month><day>-<hour><minute><second>-<originalfilename>

In the above example, I rotate every 1 second, which isn't a good idea. You probably want something like every 5 minutes:
--rotate 300
or
--rotate 5m

When I do my scans, I always rotate them hourly, or:
--rotate hourly
or
--rotate 60m
or
--rotate 3600

One thing this does is ALIGN the output on the nearest boundary, so that if you rotate "hourly", it' close the file and start a new one at the start of the next hour. In other words, if you start a scan 46 minutes past the hour, the first rotation will happen in 14 minutes.

You can also rotate on file size. To rotate every 10kilobytes:
--rotate-size 10k
or
--rotate-size 10240

Of course 'm' means megabytes, 'g' gigabytes, and so forth.

You can also put them in a directory. In my file `/etc/masscan/masscan.conf` I have the line:
rotate-dir = /var/log/masscan

Beware that when you do this, the files disappear from the current directory. I often scratch my head why I'm getting no output from a scan because I forget I've set the rotation to move them to /var/log/masscan.
