### ISSUE TITLE
How to Statically Linked Masscan in Makefile?

### ISSUE THREAD

**Issue by Droid-MAX** [robertdavidgraham/masscan#477]
compile for arm linux platform devices. 
how to statically link libpcap library into masscan?

**Comment by Droid-MAX** [comment]
compile for arm linux platform devices

**Comment by mzpqnxow** [comment]
You'll need a toolchain that can build arm, that's beyond the scope of a masscan issue.. but, assuming you have that, you will need to take a look at the changes that made masscan dynamically load things like pf_ring libraries, pcap libs, etc.

You can try simply adding `-DSTATICPCAP` to the `CFLAGS`. Otherwise, grep for `STATICPCAP` in the source, or any use of `dlopen`. You will need to not rely on `dlopen` if you want the executable to work properly when statically linked.

**Comment by Droid-MAX** [comment]
![S00308-130915](https://user-images.githubusercontent.com/12762435/76157053-c5a4cd00-613e-11ea-958f-b82a3e056c3e.jpg)

Looks like I have to modify the source file.

**Comment by mzpqnxow** [comment]
> ![S00308-130915](https://user-images.githubusercontent.com/12762435/76157053-c5a4cd00-613e-11ea-958f-b82a3e056c3e.jpg)
> 
> Looks like I have to modify the source file.

Yes, changes to both the source code and the Makefile will be required. I suggest forking it and starting a branch with a Makefile that allows building via the build time linking method or the runtime linking method via a target for each.

**Comment by Margular** [comment]
I have made a statically linked masscan, you can check it here: https://github.com/Margular/masscan/tree/dev
