### ISSUE TITLE
Port range and single port scan results are different,

### ISSUE THREAD

**Issue by xiaoqi7654321** [robertdavidgraham/masscan#588]
[root@localhost bin]# ./masscan -p 3307 xxx.xxx.xxx.xxx --rate 50000 --wait 0  
Starting masscan 1.3.2 (http://bit.ly/14GZzcT) at 2021-05-13 02:44:28 GMT
Initiating SYN Stealth Scan
Scanning 1 hosts [1 port/host]
Discovered open port 3307/tcp on xxx.xxx.xxx.xxx                                 
[root@localhost bin]# ./masscan -p 1-65535 xxx.xxx.xxx.xxx --rate 50000 --wait 0  
Starting masscan 1.3.2 (http://bit.ly/14GZzcT) at 2021-05-13 02:44:41 GMT
Initiating SYN Stealth Scan
Scanning 1 hosts [65535 ports/host]

Did I write something wrong ?
Please help me find out the problem
thanks

**Comment by robertdavidgraham** [comment]
That's a good question.

The cause is that you are flooding the target with too many packets, and thus, the response is getting lost. You might be triggering SYN flood defenses in the target.

Rates like 50,000 packets-per-second are intended when scanning a wide range of machines. Using high rates against a single target is problematic.
