### ISSUE TITLE
Internet dropping problem while using masscan

### ISSUE THREAD

**Issue by DarkneSsDz** [robertdavidgraham/masscan#656]
hello, so there seems to be a problem while using masscan on windows ( didn't try it on linux yet ),
after starting the scan with like 1 minute the internet drops from the router and even masscan keeps struggling to not say stopping from work, i heard this is related to NAT option on router or something like there did anyone here faced such problem before ? and if yes can you share your fix with me and others who has same problem? 
Thanks in advance ^^

**Comment by dingusgh** [comment]
masscan is not designed to "scan the whole internet from a home/residential computer"...its designed to do this from a specific type of set up where you have an ISP that is friendly to you, has given you a connection directly on the internet (no NAT, probably no modems, etc), and you are paying for the bandwidth to do so.  that being said, i use masscan to scan myself all the time (not the whole internet) from a home set up.  my set up never includes running masscan from a system with wifi as its connection type, i select a reasonable size of IP addresses to scan, and of course, i never scan anything im not legally allowed to scan  ;-) 

this video has a great overview of some of the challenges that arose while trying to scan the whole internet
https://www.youtube.com/watch?v=nX9JXI4l3-E
i think about 23 minutes in is where they talk about ISP related stuff

overall though...masscan is going to vomit millions or even hundreds of millions of syn packets on to your local network...if your home network and your connection to your ISP and its connection to its peer (and so on) are not designed to handle that then yeah, youre going to have a bad time.  for example, if you have a network that NATs each syn packet that leaves your home network out to the internet, then you better be able to NAT hundreds of millions of syn packets because thats what masscan can generate. it gets even worse when you NAT to your ISP and your ISP NATs to its peer.  for example, are you running 192.168.0.0/24 subnet at home, and connecting to a cable modem with a 10.42.42.0/24 subnet, and when you visit a webpage it reports your IP as some non rfc1918 number that never changes?  yeah, that is probably double NAT and you have no hope of scanning the internet in under 10 minutes with this configuration

**Comment by DarkneSsDz** [comment]
@dingusgh i appreciate your explanation that's much cleaner now and i have an idea on what to do again appreciated ^^

**Comment by mynote** [comment]
Actually that answer doesn't make sense, It only drops (and also crashes Fritzbox) when using windows, regardless of the rate.

I guess it has something to-do with winpcap since there ain't any crashes on Linux.

Tested the same using a Windows-VMWare on Windows = Crashes whole fritz.
Tested the same using a Windows-VMWare on Linux = Only VMWare drops.
