### ISSUE TITLE
Generate paused.conf from partial output (masscan stopped unexpectedly)

### ISSUE THREAD

**Issue by jra89** [robertdavidgraham/masscan#661]
Hello!

I was wonder if it's possible to generate the paused.conf file from the output file?
My scenario is that I have been scanning from a cloud VM for a while and because of a problem they just shut off the VM, meaning that the paused.conf was never generated. The output file is there and has the last found hosts in it, so surely there should be a way to generate a paused.conf from that? It doesn't need to be 100% accurate, as long as I don't have to restart from 0.

Thoughts?

**Comment by mzpqnxow** [comment]
In short, no, not really

Unless you specified the random seed on the command line (--seed) and saved that value, you're out of luck

Even *with* the seed it would be a bit of work to get the value you need, you would need to run a dummy scan with --offline and interrupt the scan (programmatically) when it reached the IP address of the final result in your output file

A tip for the future, rather than having to deal with this issue while also avoiding needing to manually split your targets into groups or muck around with --seed, you could run masscan in sharded mode. This way you can break the scan into many smaller scans, without sacrificing the randomness or doing any arbitrary splitting of your target space

**Comment by jra89** [comment]
Alright, thank you! : )

I have started using shards which works perfectly.
