### ISSUE TITLE
Debian 6.0.10 

### ISSUE THREAD

**Issue by sec13b** [robertdavidgraham/masscan#774]
linux2:~# lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 6.0.10 (squeeze)
Release:        6.0.10
Codename:       squeeze
linux2:~#

linux2:/opt/masscan-1.3.2# make
fatal: Not a git repository (or any of the parent directories): .git
gcc -g -ggdb    -Wall -O2 -c src/massip-addr.c -o tmp/massip-addr.o
src/massip-addr.c: In function ‘ipv6address_selftest’:
src/massip-addr.c:244: error: invalid use of non-lvalue array
src/massip-addr.c:244: warning: left-hand operand of comma expression has no effect
src/massip-addr.c:244: error: invalid operands to binary + (have ‘char[48]’ and ‘int’)
src/massip-addr.c:244: error: cannot convert to a pointer type
src/massip-addr.c:244: warning: value computed is not used
src/massip-addr.c:244: error: invalid use of non-lvalue array
src/massip-addr.c:244: error: invalid operands to binary + (have ‘char[48]’ and ‘int’)
src/massip-addr.c:244: error: cannot convert to a pointer type
src/massip-addr.c:244: error: invalid use of non-lvalue array
src/massip-addr.c:244: warning: left-hand operand of comma expression has no effect
src/massip-addr.c:244: error: invalid use of non-lvalue array
src/massip-addr.c:244: error: cannot convert to a pointer type
src/massip-addr.c:244: error: cannot convert to a pointer type
src/massip-addr.c:244: error: cannot convert to a pointer type
src/massip-addr.c:244: error: cannot convert to a pointer type
src/massip-addr.c:244: error: invalid operands to binary + (have ‘char[48]’ and ‘int’)
src/massip-addr.c:244: error: cannot convert to a pointer type
src/massip-addr.c:244: error: invalid use of non-lvalue array
src/massip-addr.c:244: error: cannot convert to a pointer type
src/massip-addr.c:244: error: invalid use of non-lvalue array
make: *** [tmp/massip-addr.o] Error 1
linux2:/opt/masscan-1.3.2#

any help ?

**Comment by mzpqnxow** [comment]
Get a newer version of gcc, or maybe try setting CC in the Makefile to use llvm/clang (CC=clang)

If you can't do either, because apt packages on Debian 6 are too old to get modern gcc or clang, the easiest way to get a modern version of gcc onto a system without building one is to use on the prebuilt tarballs from https://musl.cc

If you're on x86_64, try http://musl.cc/x86_64-linux-musl-native.tgz

Untar, then set CC to the the path to the gcc in the unpacked directory. You may need to modify the Makefile, or you may be able to use something like:

    $ make CC=/path/to/x86_64-linux-musl/bin/gcc

Or:

    $ CC=/path/to/x86_64-linux-musl/bin/gcc make

That's the best suggestion I have, aside from "upgrade to a modern distribution" 😝 

Why on earth are you using Debian 6 anyway? (Just curious)
